parameters:
    btn_news.provider.node_content.class: Btn\NewsBundle\Provider\NodeContentProvider

services:
    btn_news.provider.node_content:
        class: %btn_news.provider.node_content.class%
        arguments:
            provider: @btn_news.provider.news_category
