services:

    btn_news.form.news_control:
        class: %btn_news.form.news_control.class%
        calls:
            - [setClass, ['%btn_news.news.class%']]
        tags:
            - { name: form.type, alias: btn_news_form_news_control }

    btn_news.form.news_category_control:
        class: %btn_news.form.news_category_control.class%
        calls:
            - [setClass, ['%btn_news.news_category.class%']]
        tags:
            - { name: form.type, alias: btn_news_form_newscategorycontrol }

    btn_news.form.type.news_category:
        class: %btn_news.form.type.news_category.class%
        calls:
            - [setClass, ['%btn_news.news_category.class%']]
            # - [setEntityManager, ['@doctrine.orm.entity_manager']]
        tags:
            - { name: form.type, alias: btn_newscategory }
