_btn_news_routing_control:
    resource: "@BtnNewsBundle/Resources/config/routing/control.xml"
    prefix: /control

_btn_news_routing_front:
    resource: "@BtnNewsBundle/Resources/config/routing/front.xml"
    prefix: /
