services:
    btn.news.content_provider:
        class: Btn\NewsBundle\Service\NewsContentProvider
        arguments:
            router: '@router'
            em:     '@doctrine.orm.entity_manager'

    btn.newscategory.manager:
        class: Btn\NewsBundle\Service\NewsCategoryManager
        arguments:
            em:          '@doctrine.orm.entity_manager'
            paginator:   '@knp_paginator'
            twig:        '@twig'
            formFactory: '@form.factory'

    btn_newsbundle.form.type.news_category:
        class: Btn\NewsBundle\Form\Type\NewsCategoryType
        tags:
            - { name: form.type, alias: btn_newsbundlebundle_news_category }
