services:

    btn_news.newscategory.manager:
        class: Btn\NewsBundle\Service\NewsCategoryManager
        arguments:
            em:          '@doctrine.orm.entity_manager'
            paginator:   '@knp_paginator'
            twig:        '@twig'
            formFactory: '@form.factory'

    btn_news.form.type.news_category:
        class: Btn\NewsBundle\Form\Type\NewsCategoryType
        tags:
            - { name: form.type, alias: btn_news_news_category }
