services:
    #add link to the CP top menu
    btn_news.menu_navbar.news_section:
        class: %btn_admin.menu_item.class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "btn_news.menu_navbar.news_section", "btn_news_newscontrol_index", [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_admin.menu_navbar.modules }

    btn_news.menu_navbar.news_section.news_item:
        class: %btn_admin.menu_item.class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "btn_news.menu_navbar.news_section.news_item", "btn_news_newscontrol_index", [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_news.menu_navbar.news_section }

    btn_news.menu_navbar.news_section.newscategory_item:
        class: %btn_admin.menu_item.class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "btn_news.menu_navbar.news_section.newscategory_item", "btn_news_newscategorycontrol_index", [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_news.menu_navbar.news_section }
