services:
    btn_news.provider.news:
        class: %btn_base.provider.entity.class%
        parent: btn_base.provider.abstract_entity
        arguments: ['%btn_news.news.class%']

    btn_news.provider.news_category:
        class: %btn_base.provider.entity.class%
        parent: btn_base.provider.abstract_entity
        arguments: ['%btn_news.news_category.class%']
