<?php

namespace Btn\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Btn\NewsBundle\Entity\NewsCategory;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{

    /**
     * Get array of last news
     *
     * @param  integer $count
     * @return array
     */
    public function getLastNews($count = null)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM BtnNewsBundle:News n ORDER BY n.created_at DESC')
        ;

        $count = (int) $count;
        if ($count) {
            $query->setMaxResults($count);
        }

        return $query->getResult();
    }

    /**
     * Get array of last news from category
     *
     * @param  integer $count
     * @param  integer $count
     * @return array
     */
    public function getLastNewsFromCategory(NewsCategory $category, $count = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.category = :category')->setParameter(':category', $category)
            ->orderBy('n.created_at', 'DESC')
        ;

        $query = $qb->getQuery();

        $count = (int) $count;
        if ($count) {
            $query->setMaxResults($count);
        }

        return $query->getResult();
    }

    /**
     *
     */
    public function getMontsWithYears(NewsCategory $category = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->select('SUBSTRING(n.created_at, 6, 2) as month, SUBSTRING(n.created_at, 1, 4) as year')
            ->groupBy('year, month')
            ->orderBy('n.created_at', 'DESC')
        ;

        if (null != $category) {
            $qb->addWhere('n.category = :category')->setParameter(':category', $category);
        }

        $q = $qb->getQuery();

        return $q->getResult();
    }
}
