<?php

namespace Btn\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Btn\NewsBundle\Entity\NewsCategory;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    /**
     *
     */
    public function getBaseQueryBuilder()
    {
        return $this->createQueryBuilder('n')->orderBy('n.created_at', 'DESC');
    }

    /**
     *
     */
    public function getNewsForCategoryQueryBuilder(NewsCategory $category = null)
    {
        $qb = $this->getBaseQueryBuilder();

        if ($category) {
            $qb->where('n.category = :category')->setParameter(':category', $category);
        }

        return $qb;
    }

    /**
     * Get array of last news
     *
     * @param  integer $count
     * @return array
     */
    public function getLastNews($count = null, NewsCategory $category = null)
    {
        $qb = $this->getBaseQueryBuilder();

        if ($category) {
            $qb->where('n.category = :category')->setParameter(':category', $category);
        }

        $query = $qb->getQuery();

        $count = (int) $count;
        if ($count) {
            $query->setMaxResults($count);
        }

        return $query->getResult();
    }

    /**
     *
     */
    public function getMonthsWithYears(NewsCategory $category = null)
    {
        $qb = $this->getBaseQueryBuilder()
            ->select('SUBSTRING(n.created_at, 6, 2) as month, SUBSTRING(n.created_at, 1, 4) as year')
            ->groupBy('year, month')
        ;

        if (null != $category) {
            $qb->addWhere('n.category = :category')->setParameter(':category', $category);
        }

        $q = $qb->getQuery();

        return $q->getResult();
    }

    /**
     *
     */
    public function getNewsFromYearMonthQueryBuilder($year, $month, NewsCategory $category = null)
    {
        $qb = $this->getBaseQueryBuilder()
            ->where('n.created_at LIKE :date')->setParameter(':date', $year . '-' . $month . '%')
        ;

        if (null != $category) {
            $qb->addWhere('n.category = :category')->setParameter(':category', $category);
        }

        return $qb;
    }
}
